import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Match,STEP,FLOOR,LEFT,RIGHT,GOAL_TOP,R} from './engine.mjs';
import {Controls} from './input.mjs';
const run=(m,seconds,input={})=>{for(let i=0;i<seconds/STEP;i++){m.step(STEP,input);m.events.length=0;}};
const fresh=()=>{const m=new Match(()=>.6);m.start();run(m,2.5);return m;};
test('countdown, exact 90-second play clock, result and restart',()=>{const m=fresh();assert.equal(m.state,'playing');m.time=.03;run(m,.04);assert.equal(m.state,'ended');assert.equal(m.time,0);m.start();assert.deepEqual(m.scores,[0,0]);assert.equal(m.time,90);assert.equal(m.state,'countdown');});
test('movement plus jump plus kick, deceleration and one kick per action',()=>{const m=fresh(),p=m.players[0];m.ball={x:p.x+65,y:p.y-35,vx:0,vy:0,spin:0};m.action('jump');m.action('kick');m.step(STEP,{right:true});assert.ok(p.x>360);assert.ok(p.y<FLOOR);assert.ok(m.ball.vx>700);assert.equal(m.events.filter(e=>e.type==='kick').length,1);run(m,.15,{right:true});run(m,.12);assert.equal(p.vx,0);run(m,1);assert.equal(p.y,FLOOR);assert.equal(p.kickBuffer,0);});
test('goals on both sides require whole ball and reset only once',()=>{const m=fresh();m.ball={x:RIGHT+R-1,y:350,vx:0,vy:0,spin:0};m.step(STEP);assert.equal(m.state,'playing');m.ball.x=RIGHT+R+1;m.step(STEP);assert.deepEqual(m.scores,[1,0]);run(m,2.2);assert.deepEqual(m.scores,[1,0]);assert.equal(m.ball.x,600);run(m,1.3);m.ball={x:LEFT-R-2,y:350,vx:0,vy:0,spin:0};m.step(STEP);assert.deepEqual(m.scores,[1,1]);});
test('crossbar reflects a fast ball; roof stops a ball above the net',()=>{const m=fresh();m.ball={x:RIGHT-23,y:GOAL_TOP,vx:1000,vy:0,spin:0};run(m,.025);assert.ok(m.ball.vx<0);assert.deepEqual(m.scores,[0,0]);m.ball={x:1140,y:GOAL_TOP-22,vx:0,vy:900,spin:0};run(m,.02);assert.ok(m.ball.y<GOAL_TOP);assert.ok(m.ball.vy<0);assert.deepEqual(m.scores,[0,0]);});
test('ball settles without floor jitter and escapes exact player overlap',()=>{const m=fresh();m.ball={x:600,y:FLOOR-R,vx:10,vy:0,spin:0};for(let i=0;i<500;i++)m.physics(STEP,false);assert.equal(m.ball.y,FLOOR-R);assert.equal(m.ball.vy,0);assert.equal(m.ball.vx,0);m.ball.x=m.players[0].x;m.ball.y=m.players[0].y-67;m.physics(STEP);assert.ok(Number.isFinite(m.ball.x));assert.ok(Math.abs(m.ball.x-m.players[0].x)>5);});
test('pause freezes time and physics',()=>{const m=fresh();m.state='paused';const before=JSON.stringify(m);run(m,3);assert.equal(JSON.stringify(m),before);});
test('ten complete matches, no non-finite positions or scores counted twice',()=>{let seed=13;const m=new Match(()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;});for(let round=0;round<10;round++){m.start();let steps=0;while(m.state!=='ended'&&steps<30000){if(steps%65===0)m.action('kick');if(steps%160===0)m.action('jump');const right=m.ball.x>m.players[0].x;m.step(STEP,{right,left:!right});m.events.length=0;assert.ok(Number.isFinite(m.ball.x)&&Number.isFinite(m.ball.y));assert.ok(m.ball.y<=FLOOR-R+.001);steps++;}assert.equal(m.state,'ended');assert.ok(m.scores[0]+m.scores[1]<65);}});
test('pointer multitouch, cancellation, key repeat and mixed sources',()=>{const win=new EventTarget();globalThis.window=win;class Button extends EventTarget{constructor(name){super();this.dataset={control:name};this.classList={toggle(){}};}setPointerCapture(){}}
 const buttons=['left','right','jump','kick'].map(n=>new Button(n)),actions=[],input=new Controls({querySelectorAll:()=>buttons},a=>actions.push(a),()=>true);
 const pointer=(b,type,id)=>{const e=new Event(type,{cancelable:true});e.pointerId=id;b.dispatchEvent(e);};const key=(type,code)=>{const e=new Event(type,{cancelable:true});e.code=code;win.dispatchEvent(e);};
 pointer(buttons[1],'pointerdown',1);pointer(buttons[2],'pointerdown',2);pointer(buttons[3],'pointerdown',3);assert.equal(input.state.right,true);assert.deepEqual(actions,['right','jump','kick']);pointer(buttons[2],'pointercancel',2);assert.equal(input.state.right,true);pointer(buttons[1],'pointerup',1);assert.equal(input.state.right,false);pointer(buttons[3],'lostpointercapture',3);assert.equal(input.pointers.size,0);
 key('keydown','KeyJ');key('keydown','KeyJ');assert.equal(actions.filter(a=>a==='kick').length,2);key('keyup','KeyJ');key('keydown','KeyD');pointer(buttons[1],'pointerdown',4);key('keyup','KeyD');assert.equal(input.state.right,true);win.dispatchEvent(new Event('blur'));assert.equal(input.state.right,false);assert.equal(input.pointers.size,0);delete globalThis.window;
});
